### ISSUE TITLE
Add UI tests (OSOE-616)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-Core-API-Client#24]
Add tests that run the Tester app and test all the operations with a running Orchard Core application. This then needs to be run as part of OSOCE.

`IOrchardCoreApi.CustomEditAsync()` needn't be tested, see https://github.com/Lombiq/Orchard-Core-API-Client/issues/30.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-616)

**Comment by Piedone** [comment]
Something you might be interested in next @DAud-IcI?

**Comment by sarahelsaig** [comment]
Sure, I'm interested. But https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/issues/378 is a blocker to this for the reasons explained [here](https://github.com/Lombiq/Orchard-Core-API-Client/pull/29#discussion_r1225133089).

Also do you think we still need the tester app at all if we have UI tests? I think the ApiClient can be created inside the normal UI test body, rather than running an application. They are communicating over HTTP anyway so I don't think they have to be separate processes.

**Comment by Piedone** [comment]
Yes, we still need the tester app to be able to run the API client for quick manual tests, but the UI test doesn't need to drive that; rather, as you say, the API client can be used from the test itself (I'm calling it UI test because it's still interacting with a running app's UI, though not GUI).
